name: PluginPack
main: org.CreeperCoders.InfectedPlugin.InfectedPlugin
description: A bunch of stuff!
version: 1.00 #Don't change the version
authors: [xXWilee999Xx, buildcarter8, Paldiu, Wild1145]

commands:
  anticheat:
    description: Anticheat details
    usage: /<command>
  pluginpack:
    description: Pluginpack details
    usage: /<command>
