#Might change the name to something better.
name: PluginPack
main: org.CreeperCoders.InfectedPlugin.InfectedPlugin
description: A bunch of stuff!
version: 2.4
#Don't change the version
authors: [xXWilee999Xx, buildcarter8, Paldiu, Wild1145]

commands:
  anticheat:
    description: AntiCheat Details
    usage: /<command>
  pluginpack:
    description: PluginPack Details
    usage: /<command>
