name: PluginPack
main: org.CreeperCoders.InfectedPlugin.InfectedPlugin
description: A bunch of stuff!
#version: 1.00
#Updating the version would get stupid, no.
authors: [xXWilee999Xx, buildcarter8, Paldiu]

commands:
  anticheat:
    description: Anticheat details
    usage: /<command>
  pluginpack:
    description: Pluginpack details
    usage: /<command>
