name: PluginPack
main: org.CreeperCoders.InfectedPlugin.InfectedPlugin
description: A bunch of stuff!
commands:
  anticheat:
    description: Anticheat details
  pluginpack:
    description: Pluginpack details
